steps:
- name: 'eu.gcr.io/${PROJECT_ID}/ocmlf-builderterraformgcloud:1.0.0'
  id: End-To-End test
  env:
    - 'PROJECT_NUMBER=$PROJECT_NUMBER'
    - 'BILLING_ACCOUNT=${_BILLING_ACCOUNT}'
    - 'FOLDER_ID=${_FOLDER_ID}'
    - 'PROJECT_LABELS=${_PROJECT_LABELS}'
  entrypoint: 'bash'
  args:
    - -c
    - |
        make ci-one-click-mlflow