steps:
- name: 'eu.gcr.io/${PROJECT_ID}/ocmlf-builderterraformgcloud:1.0.0'
  id: End-To-End test
  env:
    - 'PROJECT_NUMBER=$PROJECT_NUMBER'
    - 'BILLING_ACCOUNT=${_BILLING_ACCOUNT}'
    - 'TEST=${_FOLDER_ID}'
  entrypoint: 'bash'
  args:
    - -c
    - |
        birth_project_number=$PROJECT_NUMBER make ci-one-click-mlflow