steps:
- name: 'eu.gcr.io/${_PROJECT_ID}/ocmlf-builderterraformgcloud:1.0.0'
  id: End-To-End test
  env:
    - 'PROJECT_ID=${_PROJECT_ID}'
  entrypoint: 'bash'
  args:
    - -c
    - |
        export GOOGLE_OAUTH_ACCESS_TOKEN=$(gcloud auth print-access-token --impersonate-service-account=ocmlf-ci-sa@${PROJECT_ID}.iam.gserviceaccount.com)
        CI_PROJECT_ID=ocmlf-github-ci-$(uuidgen)
        gcloud projects create $CI_PROJECT_ID --name=ocmlf-github-ci
        make validate-terraform && \
        echo -e "${CI_PROJECT_ID}\1\\4\y" | make one-click-mlflow && \
        make destroy && \
        gcp projects delete $CI_PROJECT_ID