steps:
- name: 'eu.gcr.io/${PROJECT_ID}/ocmlf-builderterraformgcloud:1.0.0'
  id: End-To-End test
  env:
    - 'FOLDER_ID=${_FOLDER_ID}'
    - 'BILLING_ACCOUNT=${_BILLING_ACCOUNT}'
    - 'PROJECT_NUMBER=$PROJECT_NUMBER'
  entrypoint: 'bash'
  args:
    - -c
    - |
        folder_id=$FOLDER_ID billing_account=$BILLING_ACCOUNT birth_project_number=$PROJECT_NUMBER make ci-one-click-mlflow